services:

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_comunnity
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-demo

  mail-dev:
    container_name: mail-dev-bc
    image: maildev/maildev
    ports:
      - 1080:1080
      #puerto que envia correo
      - 1025:1025

  adminer_db:
    container_name: adminer_db
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8090
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local


